### ISSUE TITLE
node16 actions are deprecated

### ISSUE THREAD

**Issue by markstos** [kevincobain2000/action-cache-http#17]
This needs to be moved to a newer engine version.

**Comment by kevincobain2000** [comment]
Oh. People use this action?
Will do sometime this weekend

**Comment by kevincobain2000** [comment]
pushed to v3.2
Will override v3 if v3.2 works well for you

**Comment by markstos** [comment]
Ha, maybe I'm on the only user? Is there a better choice these days? When I added it, it seemed to clearly be the best choice to solve a problem for self-hosted runners.

**Comment by kevincobain2000** [comment]
I use it for some repos still. But then I moved to https://github.com/kevincobain2000/action-coveritup 
A slightly different metric to calculate and track real time taken. You might like it.
