### ISSUE TITLE
README, releases out of date

### ISSUE THREAD

**Issue by markstos** [kevincobain2000/action-cache-http#5]
The README explicitly says to use `@v2`, and the `Releases` area on the side also confirms that `v2` is the latest release, but from looking at "Tags", it appears that @v2.3 is.

Attempting to follow the syntax in the README can result in unclear errors like:

```
/__w/_actions/kevincobain2000/action-cache-http/v2/cache-http.sh: 33: [: =: unexpected operator
 1: 0x9da7c0 node::Abort() [/__e/node12/bin/node]
 2: 0xa4e219  [/__e/node12/bin/node]
/__w/_actions/kevincobain2000/action-cache-http/v2/cache-http.sh: 33: [: =: unexpected operator
```

My clue something was off was the line numbers in the error didn't match what was on Github. It would be helpful if new releases were tagged as Github release and the README was updated as well.

Thanks!

**Comment by markstos** [comment]
The README has been updated, and there's been a v3 release that's tagged, but the "Releases" page still shows v2 as the latest release:

https://github.com/kevincobain2000/action-cache-http/releases

It may be useful to use a tool like "release-it" which helps coordinate all the details of making a release to keep everything consistent.

**Comment by kevincobain2000** [comment]
missing v3 https://github.com/kevincobain2000/action-cache-http/releases/tag/v3
